name: Cleanup Container Registry
on:
  push:
    branches:
      - 'feature/*'

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: myservice

jobs:
  cleanup:
    name: Cleanup GCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Create Docker Tags
        run: echo "IMAGE=gcr.io/$PROJECT_ID/$SERVICE_NAME" >> $GITHUB_ENV

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true

      - name: Get Service Revision images
        run: |-
          gcloud run revisions list \
            --service "$SERVICE_NAME" \
            --region "$RUN_REGION" \
            --format "csv[no-heading](spec.containers.image)" \
            | awk -F: '{print $2}' \
            > image_tags.txt

      - name: Get Container Tags
        run: |-
          gcloud container images list-tags "$IMAGE" \
            --format "csv[no-heading](TAGS)" \
            > tags.txt

      - name: Grep Matches image_tags->tags
        run: |-
          echo "TAGS=`grep -v -f image_tags.txt tags.txt \
          | awk -vORS=, '{ print $1 }' \
          | sed 's/,$//'`" >> $GITHUB_ENV

      - name: Printout Tags
        run: echo "$TAGS"
