name: Google Cloud Run Revision Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: myservice
  PR_NUMBER: echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'
  SHA_SHORT: git rev-parse --short HEAD

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Install Dependencies
        run: go get -d -v

      - name: Run Tests
        run: go test ./...

      - name: Build
        run: go build -v .

  deploy-gcr:
    name: Deploy Revision Tag to GCR
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}

      # Build and push image to Google Container Registry
      - name: Build & Push
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$PR_NUMBER-$SHA_SHORT"

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$PR_NUMBER-$SHA_SHORT" \
            --platform "managed" \
            --allow-unauthenticated
            --tag pr-$PR_NUMBER
            --no-traffic
