name: Google Cloud Run PR Close Cleanup
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: myservice
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  cleanup:
    name: GCR PR Merge Cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true

      - name: Remove PR Tags
        run: |-
          gcloud run services update-traffic "${SERVICE_NAME}" \
            --region "${RUN_REGION}" \
            --remove-tags "pr-${PR_NUMBER}"
