name: Google Cloud Run PR Close Cleanup
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: myservice

jobs:
  cleanup:
    name: GCR PR Merge Cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Create Env Variables
        run: |
          echo "PR_NUMBER=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'`" >> $GITHUB_ENV

      - name: Create Docker Tag
        run: |-
          echo "IMAGE_REGX=gcr.io/$PROJECT_ID/$SERVICE_NAME:$PR_NUMBER-*" >> $GITHUB_ENV

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true

      # - name: Remove PR Tags
      #   run: |-
      #     gcloud run services update-traffic "${SERVICE_NAME}" \
      #       --region "${RUN_REGION}" \
      #       --remove-tags "pr-${PR_NUMBER}"

      - name: Set Revisions Env Variable
        run: |-
          echo "REVISIONS=`gcloud run revisions list \
            --service "${SERVICE_NAME}" \
            --region "${RUN_REGION}" \
            --filter "spec.containers.image ~ ${IMAGE_REGX}" \
            --format "csv[no-heading](metadata.name)" \
            --sort-by=~metadata.name \
            | awk -vORS=, '{ print $1 }' \
            | sed 's/,$//' \
            | sed 's/^[^,]*=//'`" >> $GITHUB_ENV

      # Skip most recent revision (unable to delete)
      - name: Delete unused revision instances
        run: |-
          for revision in $(echo $REVISIONS | sed "s/,/ /g")
          do
            gcloud run revisions delete "${revision}" --region "${RUN_REGION}" --quiet
          done
