name: Google Cloud Run PR Close Cleanup
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: myservice

jobs:
  cleanup:
    name: GCR PR Merge Cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Create Env Variables
        run: |
          echo "PR_NUMBER=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'`" >> $GITHUB_ENV
          echo "SHA_SHORT=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true

      - name: List Revisions
        run: |-
          gcloud run revisions list \
            --service "${SERVICE_NAME}" \
            --region "${RUN_REGION}" \
            --filter "tags.items=pr-${PR_NUMBER}"
